### ISSUE TITLE
Paste HTML not same as expected

### ISSUE THREAD

**Issue by adesm** [WendellAdriel/jodit-vue#11]
when I copy this HTML
`<blockquote class="twitter-tweet"><p lang="en" dir="ltr">SRAM has been working on a truly radical front derailleur design; one that&#39;s incorporated into the crankset itself, rather than attached to the frame. Game-changer? <a href="https://t.co/DRvAUQOMRS">https://t.co/DRvAUQOMRS</a> <a href="https://t.co/JIyxrcYdQT">pic.twitter.com/JIyxrcYdQT</a></p>&mdash; CyclingTips (@cyclingtips) <a href="https://twitter.com/cyclingtips/status/1273111580952182785?ref_src=twsrc%5Etfw">June 17, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

then I paste that HTML using keyboard command (ctrl+v / command+v), but the result not as expected. when I see on source code mode
that HTML look like
`<meta charset="utf-8"><span style="color: rgb(136, 153, 166); font-family: &quot;Helvetica Neue&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: nowrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(225, 232, 237); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">&lt;blockquote class="twitter-tweet"&gt;&lt;p lang="en" dir="ltr"&gt;SRAM has been working on a truly radical front derailleur design; one that&amp;#39;s incorporated into the crankset itself, rather than attached to the frame. Game-changer? &lt;a href="https://t.co/DRvAUQOMRS"&gt;https://t.co/DRvAUQOMRS&lt;/a&gt; &lt;a href="https://t.co/JIyxrcYdQT"&gt;pic.twitter.com/JIyxrcYdQT&lt;/a&gt;&lt;/p&gt;&amp;mdash; CyclingTips (@cyclingtips) &lt;a href="https://twitter.com/cyclingtips/status/1273111580952182785?ref_src=twsrc%5Etfw"&gt;June 17, 2020&lt;/a&gt;&lt;/blockquote&gt; &lt;script async src="https://platform.twitter.com/widgets.js" charset="utf-8"&gt;&lt;/script&gt;</span>`

so in text mode I see unexpected result
<img width="872" alt="Screen Shot 2020-06-17 at 17 40 20" src="https://user-images.githubusercontent.com/15310254/84888601-b6300b00-b0c1-11ea-9199-68404b07a36a.png">

expected result
<img width="831" alt="Screen Shot 2020-06-17 at 17 42 12" src="https://user-images.githubusercontent.com/15310254/84888722-e7a8d680-b0c1-11ea-9a75-db11f147aef8.png">

why when I paste some HTML and KEEP AS HTML, this editor always wrapped the HTML by 'meta, span, etc'.
why? how to avoid 'meta meta span span' ?

**Comment by WendellAdriel** [comment]
Hello, @adesm 
Did you test it on the Jodit Editor directly (without using this Vue wrapper) to see if it's an issue with the wrapper or the editor itself?

**Comment by adesm** [comment]
I already test in jodit playground, and it was the same. the editor show unexpected result. the result wrapped by <meta charshet...<span>[copy paste HTML]<span>

**Comment by adesm** [comment]
I found something. When I remove <script> tag in that blockquote HTML. the editor show as expected. But when the script tag exist, the editor wrap the HTML using meta tag and escaping the HTML.

How to config script tag or something?
How to add before paste HTML in vue component, remove script tag?

**Comment by WendellAdriel** [comment]
Since this is happening in the editor itself, I would ask you to create an issue on the editor repository: https://github.com/xdan/jodit

This wrapper is only to "wrap" the editor functionalities to use as a Vue element. When the editor fixes this issue, this wrapper will get the updates.

Thanks for helping.
