### ISSUE TITLE
Jodit 3.6: Word/HTML insert dialog does not open

### ISSUE THREAD

**Issue by Scaenicus** [WendellAdriel/jodit-vue#24]
# Version [Jodit 3.6.8](https://github.com/xdan/jodit/releases/tag/3.6.8)

There are new dialogues in Jodit which try to render fullscreen modals.

Those seem to be prevented by jodit-vue.

![image](https://user-images.githubusercontent.com/1033699/114553465-f1f61b80-9c65-11eb-851b-2742bc2a30ff.png)

![image](https://user-images.githubusercontent.com/1033699/114553518-ff130a80-9c65-11eb-9847-b0d95e342907.png)

# Temporary solution

Prevent Jodit from asking and define paste-defaults.

```js
            let joditConfig = {
                "askBeforePasteFromWord": false,
                "askBeforePasteHTML": false,
                "defaultActionOnPaste": "insert_as_html",
                "defaultActionOnPasteFromWord": "insert_as_html",
                "processPasteFromWord": true,
                "processPasteHTML": true,
```

**Thank you for your work with jodit-vue!**

**Comment by Scaenicus** [comment]
Different default values:

https://xdsoft.net/jodit/doc/types/InsertMode/

**Comment by WendellAdriel** [comment]
@Scaenicus thanks for reporting that, I'm going to take a look as soon as I have some time.
Sorry for the delay, but I had some health issues recently and I'm not having much time and energy to check here, I'll do that ASAP

**Comment by Scaenicus** [comment]
@WendellAdriel No worries, the workaround works just fine for now.
Most of the time `insert_clear_html` is needed, most users needing other functions are able to insert plaintext on their own, or even use the code editor.

Take care of your health!

**Comment by WendellAdriel** [comment]
Thank you so much, @Scaenicus.
Also, I released yesterday a new version of the wrapper, can you check if the issue persists?

**Comment by Scaenicus** [comment]
Certainly.

## Testing with `"jodit-vue": "^2.4.0"` (Lock file version `2.4.0`)
**Summary**: Seems to work perfectly. Thank you!

### Changes to config-object
```
                "askBeforePasteFromWord": true,     // <----
                "askBeforePasteHTML": true,         // <----
                "defaultActionOnPaste": "insert_clear_html",
                "defaultActionOnPasteFromWord": "insert_clear_html",
                "processPasteFromWord": true,
                "processPasteHTML": true,
```

### Test
Test is on a purposefully over-encumbered development page, which usually reveals strange interactions and racing conditions.

#### HTML text with images right from a random page
+ Modal shows
+ All button variants work
  + HTML looks horrible but that's an issue with the random source... technically it works.

#### Formatted text from Libre Office's Writer
+ Was interpreted by jodit as HTML, otherwise works perfectly.

#### Formatted text from MS Office's Word
 + I have reports that it works now.
 + Later this day I will retest on the machine with an Microsoft Office license on my own.
 + **Edit**: Tested myself too, works fine!

**Comment by Scaenicus** [comment]
fix: Jodit version 3.6.8 insert-modals are now shown again for HTML and MS Word.

**Comment by WendellAdriel** [comment]
That's amazing @Scaenicus, thank you so much for your help here!!! I really appreciate it!

**Comment by Scaenicus** [comment]
You are welcome. Thank you for maintaining this great wrapper!
