### ISSUE TITLE
Library broken after latest Jodit export update

### ISSUE THREAD

**Issue by dbettini** [WendellAdriel/jodit-vue#4]
Jodit has (mistakenly, I hope) changed the way they do the export in the latest patch version, as described in [this issue](https://github.com/xdan/jodit/issues/131). Since this library uses `^3.2.21` semver, it includes all patches for Jodit, so it's basically broken for everyone that has the version of Jodit higher than `3.2.31`. 

The temporary fix for this library would be locking the version to `3.2.31`, until Jodit fixes their export (assuming they don't plan to keep the named export, but I don't see a reason for it, it just breaks backwards compatibility). 

For anyone that finds this issue before any fixes are made, just explicitly install Jodit version `3.2.31` in your project, and this library will work as well.

**Comment by WendellAdriel** [comment]
Oh, I didn't know about that.
I'll check Jodit repo and if I don't see any news on that I'll lock the version, thank you so much!!!

**Comment by dbettini** [comment]
Seems it was [ninja-fixed](https://github.com/xdan/jodit/issues/131#issuecomment-477114729)

**Comment by WendellAdriel** [comment]
LOL, hahahahaha
I was waiting because they said the fix would be quick, but I'm glad that's already fixed 👍 
Just to be sure, the fix was on version 3.2.44?

**Comment by dbettini** [comment]
Looking at the commits, seems to be 3.2.43

**Comment by WendellAdriel** [comment]
@dbettini I added you on the all contributors list and published a new version of the lib changing the min Jodit version
