### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by fwiwDev** [WendellAdriel/jodit-vue#45]
Thanks for this library. It is super helpful and quite capable. I am looking for how to get the component to know I am using it in dark mode so it can adjust the background. Is that possible?

Now, when I use the component in dark mode and it pops up a modal, it is light text on light background (have to select it to see it).

Here is an example with the text selected so you can see it.
![image](https://user-images.githubusercontent.com/57578058/170515540-2a20a8a0-8a7f-4e58-936a-48d95cb123bc.png)

Is dark mode support a new feature or do I just need to know how to tell the component to render for dark mode?

Thanks again!

**Comment by WendellAdriel** [comment]
@fwiwDev you can check on how to customize Jodit theme here: https://xdsoft.net/jodit/pro/docs/customisation/theme.md or you can simply create styles overriding the Jodit classes for that.

**Comment by fwiwDev** [comment]
Perfect. Thanks so much. Please go ahead and close the issue. I got it working!!

**Comment by WendellAdriel** [comment]
That's great to hear @fwiwDev!!!
If you have any issues with anything else, just let me know!
