### ISSUE TITLE
Vue 3 Question

### ISSUE THREAD

**Issue by fwiwDev** [WendellAdriel/jodit-vue#48]
Hi - thanks so much for such an editor! It works quite well in my Vue 2 app and I am working on a Vue 3 app with the Composition API.

My basic sample that follows the documentation results in this Vue warn and no component:

```
Missing required prop: "value" 
  at <JoditEditor modelValue="<h1>Hello Jodit Vue</h1>" onUpdate:modelValue=fn >
```

Is jodit-vue setup to work with Vue 3 and the Composition API? If so, is there a little code sample I could be directed to please.

Thank you!

**Comment by WendellAdriel** [comment]
Hey @fwiwDev TBH I didn't test the lib with Vue 3 + Composition API yet.
Is it possible for you to get me a code example so I can take a better look at it?

**Comment by fwiwDev** [comment]
Yes - most definitely. Thanks so much for looking at this @WendellAdriel!!

https://github.com/jojukin/jodit-demo

**Comment by fwiwDev** [comment]
Thanks for looking at this @WendellAdriel - any progress in getting it working with Vue 3 + Composition API?

**Comment by WendellAdriel** [comment]
Hey, @fwiwDev I still didn't get the chance to finish the tests and changes because I'm having a lot of things to do, but I'll work on it to finish it ASAP.

**Comment by WendellAdriel** [comment]
Sorry for the HUGE delay on that, but finally version 3.0.0 was released with Vue 3 support, @fwiwDev!
