### ISSUE TITLE
cannot select text modifiers

### ISSUE THREAD

**Issue by LueNC** [WendellAdriel/jodit-vue#50]
I tried updating from jodit-vue 2.4.0 to 2.6.0 (which updates jodit from 3.8.5 to 3.20.1) and it breaks the text modifiers. You can still select text and then apply the modification by pressing the button however the modification (bold, italic etc) does not stay down when you press it i.e it does not apply to continuous typing.

**Comment by WendellAdriel** [comment]
Is this still happening @LueNC ?

**Comment by WendellAdriel** [comment]
@LueNC I'm closing this issue.
If the error is still happening, please open a new issue with the link to a project to reproduce the issue.
