### ISSUE TITLE
Importing Module breaks HMR updates

### ISSUE THREAD

**Issue by MLDMoritz** [WendellAdriel/jodit-vue#67]
Hi,

I'm using vite 4 with hmr and if I add JoditVue to my app.js it stops updating the DOM, while in console the hmr update notification still informs be about updates. Think something is interfering?

**Comment by a-di-ez** [comment]
I have same issue with vue 3, laravel mix 6 and webpack 5.72

**Comment by WendellAdriel** [comment]
Hey, @MLDMoritz and @a-di-ez can you please provide a minimal repo with the issue so I can take a look at it?

**Comment by a-di-ez** [comment]
@WendellAdriel this is part of a big project, I can show you how editor component and laravel mix config file is written

**Comment by WendellAdriel** [comment]
@a-di-ez if you could set up a minimal repo that reproduces the issue would be awesome because I have some projects running with this library but I'm not experiencing this issue

**Comment by a-di-ez** [comment]
I will try to do it tomorrow, can I send it to you in Email with a link to Google drive, so as not to post it publicly?

**Comment by WendellAdriel** [comment]
Sure, np! Thanks for the help!

**Comment by a-di-ez** [comment]
@WendellAdriel sent to me@wendelladriel.com

**Comment by WendellAdriel** [comment]
Thanks, @a-di-ez 
I'll check it out ASAP

**Comment by WendellAdriel** [comment]
@MLDMoritz @a-di-ez 
I just released a new version: 3.1.0
Can you try it out and see if this issue is fixed in the new version, please?

**Comment by a-di-ez** [comment]
@WendellAdriel great, works!

**Comment by WendellAdriel** [comment]
Great!!! Closing the issue, then! Thanks for the help! 💪
