### ISSUE TITLE
Jodit Pro Support?

### ISSUE THREAD

**Issue by saroshali4** [WendellAdriel/jodit-vue#69]
Hi @WendellAdriel

First, thank you for creating this wrapper. I was wondering how it works with Jodit Pro, we have purchased Jodit OEM license.

Do we need to install the following package separately?
[https://www.npmjs.com/package/jodit-pro](url)

I want to use a few pro plugins which comes with Jodit. I appreciate if you can give an example with an existing pro plugin of Jodit.
Thank you.

**Comment by WendellAdriel** [comment]
Hello, this package is a wrapper for the jodit free version.
I never used the Pro version and I don't have a license for it so I don't plan to support it.
